blueprint:
  name: SG Ready PV optimization (with mode selection, without utility company lockout)
  description: >
    Controls SG0/SG1 depending on PV surplus and mode selection.
    In "Auto" mode, it operates according to PV logic; otherwise, it switches manually based on your selection.
    Mode selection is made via an input select (with: Auto, Standard Operation, PV Optimization, PV Boost, Grid Lockout).
  domain: automation
  input:
    pv_sensor:
      name: PV surplus sensor (Grid Power, negative reading when feeding into the grid)
      selector:
        entity:
          domain: sensor
    sg0_switch:
      name: SG0 Output
      selector:
        entity:
          domain: switch
    sg1_switch:
      name: SG1 Output
      selector:
        entity:
          domain: switch
    mode_select:
      name: SG Ready mode-Select (input_select)
      selector:
        entity:
          domain: input_select
    sg0_threshold:
      name: SG0 Switching treshold (Watt, NEGATIVE)
      default: -1000
      selector:
        number:
          min: -15000
          max: 0
          step: 100
    sg1_threshold:
      name: SG1 Switching treshold (Watt, NEGATIVE)
      default: -3000
      selector:
        number:
          min: -15000
          max: 0
          step: 100
    off_threshold:
      name: Switching treshold (Watt, NEGATIVE)
      default: -500
      selector:
        number:
          min: -15000
          max: 0
          step: 100
    delay:
      name: Switching delay (seconds)
      default: 60
      selector:
        number:
          min: 0
          max: 600
          step: 5

mode: single

trigger:
  - platform: state
    entity_id: !input mode_select

  - platform: numeric_state
    entity_id: !input pv_sensor
    below: !input sg1_threshold
    for:
      seconds: !input delay

  - platform: numeric_state
    entity_id: !input pv_sensor
    below: !input sg0_threshold
    above: !input sg1_threshold
    for:
      seconds: !input delay

  - platform: numeric_state
    entity_id: !input pv_sensor
    above: !input off_threshold
    for:
      seconds: !input delay

action:
  - choose:
      # Switch to PV mode in "Auto" mode!
      - conditions:
          - condition: state
            entity_id: !input mode_select
            state: "Auto"
        sequence:
          # Both thresholds undershot: SG0 and SG1 AN
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input pv_sensor
                    below: !input sg1_threshold
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input sg0_switch
                  - service: switch.turn_on
                    target:
                      entity_id: !input sg1_switch
          # Only SG0 threshold crossed: SG0 ON, SG1 OFF
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input pv_sensor
                    below: !input sg0_threshold
                    above: !input sg1_threshold
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input sg0_switch
                  - service: switch.turn_off
                    target:
                      entity_id: !input sg1_switch
          # Surplus almost gone: both OFF
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input pv_sensor
                    above: !input off_threshold
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input sg0_switch
                  - service: switch.turn_off
                    target:
                      entity_id: !input sg1_switch

      # In manual mode, the switch is fixed (regardless of which one):
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input mode_select
                state: "Normal operation"
              - condition: state
                entity_id: !input mode_select
                state: "PV-PV optimization"
              - condition: state
                entity_id: !input mode_select
                state: "PV-Boost"
              - condition: state
                entity_id: !input mode_select
                state: "Network block"
        sequence:
          # Always turn both off first:
          - service: switch.turn_off
            target:
              entity_id: !input sg0_switch
          - service: switch.turn_off
            target:
              entity_id: !input sg1_switch
          # Now set the appropriate mode:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input mode_select
                    state: "Normal operation"
                sequence: []
              - conditions:
                  - condition: state
                    entity_id: !input mode_select
                    state: "PV optimization"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input sg0_switch
              - conditions:
                  - condition: state
                    entity_id: !input mode_select
                    state: "PV-Boost"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input sg0_switch
                  - service: switch.turn_on
                    target:
                      entity_id: !input sg1_switch
              - conditions:
                  - condition: state
                    entity_id: !input mode_select
                    state: "Network block"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input sg1_switch
